# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            smbct's blog
tagline:          'blog'
description:      'Notes on computer science, programming, society and more.'
url:              https://smbct.github.io

# baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'smbct'
  url:            https://smbct.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

hydeout:
  repo: https://github.com/smbct

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      permalink: /blog/:title/